name: Build Genesis Plus GX

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Step 1 Download core
        uses: actions/checkout@v4

      - name: Step 2 Compile
        run: |
          make -f Makefile.libretro

      - name: Step 3 Store core
        uses: actions/upload-artifact@v4
        with:
          name: genesis-plus-gx-linux
          path: genesis_plus_gx_libretro.so
